# Generated by Django 4.2.2 on 2024-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
